sudo: required
dist: xenial

before_install:
  - sudo apt-get update
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.6

before_script:
  - psql -c 'create database sqlalchemy_searchable_test;' -U postgres

language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy-5.3.1
install:
  - pip install -e ".[test]"
script:
  - isort --recursive --diff sqlalchemy_searchable tests && isort --recursive --check-only sqlalchemy_searchable tests
  - flake8 sqlalchemy_searchable tests
  - py.test
